---
regions:
  san-francisco-downtown:
    bbox:
      top: 71.186863
      left: 4.490018
      bottom: 57.952204
      right: 31.186774
    zoom_range: [10, 16]
outputs:
  - type: terrarium
  - type: normal
sources:
  - type: etopo1
    url: https://www.ngdc.noaa.gov/mgg/global/relief/ETOPO1/data/bedrock/grid_registered/georeferenced_tiff/ETOPO1_Bed_g_geotiff.zip
  - type: norge
    url: ./norge/norge.tif
logging:
  config: logging.example.config
